###Recuperar todo
GET http://localhost:1234/movies
###Recuperar por una iD
GET http://localhost:1234/movies/dcdd0fad-a94c-4810-8acc-5f108d3b18c3
### recuperar ´por un genero jquery, GET
GET http://localhost:1234/movies?genre=Crime
### Crear una  Peli con post
POST http://localhost:1234/movies/
Content-Type: application/json
{
    "id": "241bf55d-b649-4109-af7c-0e6890ded3fc",
    "title": "Pulp Fiction",
    "year": 1994,
    "director": "Quentin Tarantino",
    "duration": 154,
    "poster": "https://www.themoviedb.org/t/p/original/vQWk5YBFWF4bZaofAbv0tShwBvQ.jpg",
    "genre": [
      "Crime",
      "Drama"
    ],
    "rate": 8.9
}
### Recuperar la información de una persona extranjera
GET http://localhost:1234/extranjeras/234567890
### Recuperar la información de una persona nacional
GET http://localhost:1234/nacionales/12425029
